[package]
name = "mischief-in-miniature"
version = "0.1.0"
edition = "2021"

[dependencies]
avian3d = { git = "https://github.com/Jondolf/avian", rev = "114554bf61320e03d778c5d8ca67e9ae381476c5" }
bevy = "0.15.0"
